### ISSUE TITLE
[REQUEST] Change vertical alignment for tilde

### ISSUE THREAD

**Issue by crinklywrappr** [fcambus/spleen#10]
Spleen vertically aligns tilde's to the top of the glyph, but it arguably looks better when centered.

**Comment by fcambus** [comment]
Thanks for the suggestion, I think it makes sense indeed.

I'm experimenting with the change and will likely end up commiting it in a few days.

**Comment by fcambus** [comment]
Fixed in 734fd650d9ca38395cca085c89d485f7729dc32e.

**Comment by Alhadis** [comment]
Thank christ for that. Just an FYI, the elevated tilde is a throwback to the typewriter days, when overstriking was used to produce accented letters: `ñ` = <kbd>n</kbd> + <kbd>backspace</kbd> + <kbd>~</kbd>.

Obviously, that's not needed anymore... 😉  But type designers won't let this anachronism die. 😞
