### ISSUE TITLE
Include an OTF version of the 5x8 font in releases

### ISSUE THREAD

**Issue by errhammr** [fcambus/spleen#11]
I really love the Spleen fonts in all their sizes and am thinking about using them for an art project or "hacker themed" things in general.
The vast majority of art and design software supports the OTF file format. The other formats in the Spleen releases don't seem to be supported as frequently, if at all.

Because of this, I'd love to see future releases including the 5x8 version in the OTF format.

**Comment by vaskark** [comment]
Seconded :)

**Comment by fcambus** [comment]
I use [bdf2sfd](https://github.com/fcambus/bdf2sfd) to generate OpenType versions of Spleen, 
and it doesn't preserve aspect ratio on fonts not proportional to 8x16, so at the moment there
is no way to generate OTF versions for the 5x8 variant.
