### ISSUE TITLE
Unicode Block "Miscellaneous Symbols and Arrows" support

### ISSUE THREAD

**Issue by kucharskim** [fcambus/spleen#12]
Are you planning to add support to Spleen for something like that? I'm asking as recently found some apps which on the console are using up/down arrows for download and upload indication:

⬇ ⬆
\xe2\xac\x87 \xe2\xac\x86
U+2B07 U+2B06

and was wondering is this Unicode block on your roadmap or maybe not?

**Comment by fcambus** [comment]
I have plans to add a large part of the [Arrows Unicode block](https://en.wikipedia.org/wiki/Arrows_(Unicode_block)). From there, I suppose it wouldn't be too difficult to add at least the arrows from the [Miscellaneous Symbols and Arrows](https://en.wikipedia.org/wiki/Miscellaneous_Symbols_and_Arrows) Unicode block, where the two characters you pointed out are located.

On a more general note, I don't consider Spleen done yet and plan to keep on adding more characters.

**Comment by fcambus** [comment]
@kucharskim It's been a while, but I would appreciate if you could point out which programs use those characters so I can test the results. Maybe adding the most used arrows would not be that much work, I will be working on that.

**Comment by kucharskim** [comment]
@fcambus I saw it initially with https://github.com/near/nearcore/ but in general the new blockchain industry is full of emoji and utf-8. I saw non-ASCII characters in substrate chains (https://github.com/paritytech/polkadot), I don't remember does https://github.com/ethereum/go-ethereum also have some non-standard (as in, non-ASCII) characters. This task specifically was triggered by nearcore.

**Comment by fcambus** [comment]
@kucharskim Thanks for the info, I started working on adding some arrows already, will commit more stuff during the following weeks.

**Comment by fcambus** [comment]
Closing this as the mentioned symbols have been added last year.

**Comment by kucharskim** [comment]
Yes, indeed it works (copy paste from XTerm):

> 33 peers ⬇ 2.06 MB/s ⬆ 2.31 MB/s
```
$ sysctl -n kern.version                                                    
OpenBSD 7.4-current (GENERIC.MP) #1626: Thu Jan 25 20:05:01 MST 2024
    deraadt@amd64.openbsd.org:/usr/src/sys/arch/amd64/compile/GENERIC.MP
```

Thanks Frederic!
