### ISSUE TITLE
Vector versions of Spleen

### ISSUE THREAD

**Issue by teahwiz** [fcambus/spleen#20]
I absolutely love this font, it would be great if it had a vector version of the font so I could use it for GTK and Firefox. The 32x64 TTF does look okay on scaling down.

**Comment by fcambus** [comment]
Release tarballs contain the fonts in various formats, including OTF: https://github.com/fcambus/spleen/releases/download/1.9.1/spleen-1.9.1.tar.gz

**Comment by teahwiz** [comment]
By Vector version, I meant a scalable font, not a bitmap font.

**Comment by fcambus** [comment]
So do I, the OTF versions are vectorized using [bdf2sfd](https://github.com/fcambus/bdf2sfd).

**Comment by teahwiz** [comment]
they look pixelized when scaling up
