### ISSUE TITLE
Spleen for u8g2

### ISSUE THREAD

**Issue by olikraus** [fcambus/spleen#24]
I just wanted to mention, that I included spleen fonts for u8g2 project (Arduino / Microcontroller monochrome display driver, https://github.com/olikraus/u8g2/wiki/gallery)

Spleen Font page in the U8g2 Wiki: https://github.com/olikraus/u8g2/wiki/fntgrpspleen

Thanks a lot for providing such a nice and clear font!

**Comment by fcambus** [comment]
Thanks for letting me know, that's great news! I addeed a new [entry](https://github.com/fcambus/spleen/commit/ea6d66f5efddfeb250ad4ddbb5db621a8cc46759) in the trivia section to mention this.
