### ISSUE TITLE
Spleen for macOS

### ISSUE THREAD

**Issue by p-i-c-o** [fcambus/spleen#27]
I downloaded the release tarball, but no .dfont files, nor are there .otf or the other windows format.

I tried downloading it via the macports library, but nothing happens.

Please elaborate on how to use it, maybe the @fcambus could create a .ttf or a more compatible font format for this?

Thanks in advance

**Comment by p-i-c-o** [comment]
Never mind, did some research on MacPorts.

SOLUTION:
Download the macports package: `sudo port install font-spleen`
Check the downloaded content: `port contents font-spleen`

**Comment by fcambus** [comment]
The release tarball is available here: https://github.com/fcambus/spleen/releases/download/2.0.0/spleen-2.0.0.tar.gz

**Comment by p-i-c-o** [comment]
> The release tarball is available here: https://github.com/fcambus/spleen/releases/download/2.0.0/spleen-2.0.0.tar.gz

Thank you, I did not find this in the releases page, maybe on my end.
