### ISSUE TITLE
Very minor correction for dos/spleen.asm (and dos/spleen.com)

### ISSUE THREAD

**Issue by tkchia** [fcambus/spleen#29]
Hello @fcambus,

In `dos/spleen.asm`, it says
```
	mov	ax, 4Ch
	int	21h
```
I believe what you meant was
```
	mov	ax, 4C00h
	int	21h
```
with the syscall number in `ah`.

(Though I suppose exiting the program via syscall `0x00` also happens to work in this case.)

Thank you!

**Comment by fcambus** [comment]
Good catch, fixed in commit f292eabac59ab8a8a48f6e6846bb566777cfe3ba.

Thanks for pointing this out!
