### ISSUE TITLE
What software you use to generate wsfont .h files? 

### ISSUE THREAD

**Issue by nerfur** [fcambus/spleen#37]
Hello, it is more of question than issue

What software you use to generate wsfont .h files?

**Comment by fcambus** [comment]
The files are manually generated in two steps:

1) Exporting the BDF files to PSF using the **gbdfed** editor, selecting only characters from the first page (Basic Latin and Latin-1 Supplement Unicode blocks).

2) Running the output through **psf2bsd** from the psftools package. The files are then edited to add empty glyphes for the C1 Controls characters in the 0x80 through 0x9F range.

**Comment by fcambus** [comment]
I added an entry in the FAQ to document the wsfont header files creation process. Thanks for bringing the issue!
