### ISSUE TITLE
Provide warning for users of xterm 341

### ISSUE THREAD

**Issue by tdm4** [fcambus/spleen#6]
Hi,

  You may wish to add to your readme that users of Xterm version 341 may run into problems displaying the Spleen font. It basically gives this error: `Selected font has no non-zero height for ISO-8859-1 encoding` and exits. The solution is to upgrade to at least version 342 or higher.

   (I ran into this trying to run Xterm 341 with Spleen font on FreeBSD 12)

Thanks!

**Comment by fcambus** [comment]
I've also been seeing this warning ever since I started working on Spleen. In practice though, I've never noticed any display issues. Did you encounter any on your side?

**Comment by tdm4** [comment]
Yeah, when attempting to use Spleen on FreeBSD 12 with Xterm version 341, it would display that error and refuse to run xterm. Once I upgraded xterm to 342 or higher, it actually ran with the Spleen font selected.

**Comment by fcambus** [comment]
It has probably been long enough now, I think we can ignore the issue.

**Comment by tdm4** [comment]
@fcambus yeah fair enough :+1:
