### ISSUE TITLE
Missing .dfont

### ISSUE THREAD

**Issue by voipyanni** [fcambus/spleen#7]
Readme.md reads:

"### Mac OS X / macOS

macOS users should use the provided `.dfont` files."

However .dfont file not in git.

Thank you.

**Comment by fcambus** [comment]
README.md also says: "release tarballs contain the fonts in the following formats: PCF, PSF (for the Linux console), and .dfont for Macintosh users." :)

**Comment by MindTooth** [comment]
<img width="630" alt="Screenshot 2019-07-06 at 09 55 54" src="https://user-images.githubusercontent.com/33870508/60753546-4ae64980-9fd4-11e9-936b-6e785f468f5c.png">

Can't seem to add 1.0.5 to Mojave.  @voipyanni Did you make it work?

**Comment by voipyanni** [comment]
> <img alt="Screenshot 2019-07-06 at 09 55 54" width="630" src="https://user-images.githubusercontent.com/33870508/60753546-4ae64980-9fd4-11e9-936b-6e785f468f5c.png">
> 
> Can't seem to add 1.0.5 to Mojave. @voipyanni Did you make it work?

I am not running Mojave yet.

**Comment by fcambus** [comment]
Does it work on pre-Mojave version? I changed the way .dfont files are generated, that might be the issue.

Could you try if the .dfont files provided in [spleen-1.0.3.tar.gz](https://github.com/fcambus/spleen/releases/download/1.0.3/spleen-1.0.3.tar.gz) work fine?

**Comment by sevan** [comment]
the .dfont files from v1.0.3 work fine on Mojave for me.

**Comment by fcambus** [comment]
Thanks for testing @sevan, I will switch back to generating .dfont files this way for the next release.

**Comment by fcambus** [comment]
I tagged [1.1.0](https://github.com/fcambus/spleen/releases/tag/1.1.0) today, switching back to generating one dfont file per size, as was the case in 1.0.3.

**Comment by MindTooth** [comment]
The latest versions work fine with Catalina.  So much in fact that I just got it [submitted](https://github.com/Homebrew/homebrew-cask-fonts/pull/1901) to Homebrew. 👍🏻
