### ISSUE TITLE
request for mid-size bitmaps

### ISSUE THREAD

**Issue by peregrinat0r** [fcambus/spleen#9]
I really like this font but find the available sizes either too big or too small for my laptop. Are there any plans for creating mid-size versions of this font? I'll be particularly happy with the 9-12 px range. If not, how could one generate such bitmaps?

**Comment by fcambus** [comment]
A few people have been hinting about a 6x12 version, but so far it hasn't materialized. I started experimenting in this direction and might have a version for testing at some point.

**Comment by peregrinat0r** [comment]
Ahh that's great. Will keep an eye out for it.
